export const siteConfig = {
  name: "Vikram Anand | Developer Portfolio",
  authorName: "Vikram Anand",
  username: "Vanand",
  // description:
  //   "Vikram Anand's portfolio - A modern, responsive Next.js portfolio for developers. This open-source template can be customized to showcase your own skills, projects, and professional experience.",
  url: "https://vanand",
  links: {
    github: "https://github.com/vikramanand52",
  },
  ogImage: "https://res.cloudinary.com/daxpmlab8/image/upload/v1764096108/vikram.jpg",
  iconIco:
    "https://res.cloudinary.com/daxpmlab8/image/upload/v1764096411/vikram-logo_uzzydt.png",
  logoIcon:
    "https://res.cloudinary.com/daxpmlab8/image/upload/v1764096411/vikram-logo_uzzydt.png",
  keywords: [
    "Vikram Anand",
    "Frontend Developer",
    "Web Developer Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Full stack developer portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
